### ISSUE TITLE
Java upgrade 1.7.0_51 - dozer inheritance mapping issue

### ISSUE THREAD

**Issue by bhawnaasnani** [DozerMapper/dozer#158]
I am getting a dozer mapping issue when I have a parent class and a subclass with getter/setter to same field but with different subclased field values.
Dozer is trying to call the getter on the parent class and so is not able to find the fields specifed in subclass.

This has been working fine in 1.7.0_7 but fails after java upgrade 1.7.0_51

Example

public class BeanMapper
{

```
private static DozerBeanMapper mapper = new DozerBeanMapper();

public static void main(String[] args)
{
    mapper.addMapping(builder);
    SearchDocument document = new SearchDocument();
    document.setId("123");
    document.setHeight("12");
    document.setFurnitureHeight("10");
    FurnitureItem item = mapper.map(document, FurnitureItem.class);

    System.out.println(item);
}

static BeanMappingBuilder builder = new BeanMappingBuilder() {
      protected void configure() {
        mapping(Item.class, SearchDocument.class, TypeMappingOptions.mapNull(false) ) 
            .fields("id", "id")
            .fields("measurement.height", "height");

        mapping(FurnitureItem.class, SearchDocument.class, TypeMappingOptions.mapNull(false)  ) 
            .fields("measurement.furnitureHeight", "furnitureHeight");

      }
    };
```

}

public abstract class Item
{

```
private String id;
private ItemMeasurement measurement;
public String getId()
{
    return id;
}
public void setId(String id)
{
    this.id = id;
}
public ItemMeasurement getMeasurement()
{
    return measurement;
}
public void setMeasurement(ItemMeasurement measurement)
{
    this.measurement = measurement;
}
@Override
public String toString()
{
    return "Item [id=" + id + ", measurement=" + measurement + "]";
}
```

}

public class FurnitureItem extends Item
{

```
public FurnitureItemMeasurement getMeasurement()
{
    return (FurnitureItemMeasurement) super.getMeasurement();
}
public void setMeasurement(FurnitureItemMeasurement measurement)
{
    super.setMeasurement(measurement);
}
```

}

public abstract class ItemMeasurement
{
    private String height;

```
public String getHeight()
{
    return height;
}

public void setHeight(String height)
{
    this.height = height;
}

@Override
public String toString()
{
    return "ItemMeasurement [height=" + height + "]";
}
```

}

public class FurnitureItemMeasurement extends ItemMeasurement
{
    private String furnitureHeight;

```
public String getFurnitureHeight()
{
    return furnitureHeight;
}

public void setFurnitureHeight(String furnitureHeight)
{
    this.furnitureHeight = furnitureHeight;
}

@Override
public String toString()
{
    return "FurnitureItemMeasurement [furnitureHeight=" + furnitureHeight + "]";
}
```

}

public class SearchDocument
{

```
private String id;
private String height;
private String furnitureHeight;
public String getId()
{
    return id;
}
public void setId(String id)
{
    this.id = id;
}
public String getHeight()
{
    return height;
}
public void setHeight(String height)
{
    this.height = height;
}
public String getFurnitureHeight()
{
    return furnitureHeight;
}
public void setFurnitureHeight(String furnitureHeight)
{
    this.furnitureHeight = furnitureHeight;
}
```

}

Exception in thread "main" org.dozer.MappingException: No read or write method found for field (measurement.furnitureHeight) in class (class com.test.dozer.types.FurnitureItem)
    at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.determinePropertyType(GetterSetterPropertyDescriptor.java:310)
    at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.getPropertyType(GetterSetterPropertyDescriptor.java:67)
    at org.dozer.fieldmap.FieldMap.getSrcFieldType(FieldMap.java:121)
    at org.dozer.loader.MappingsParser.processMappings(MappingsParser.java:108)
    at org.dozer.loader.CustomMappingsLoader.load(CustomMappingsLoader.java:49)
    at org.dozer.DozerBeanMapper.loadCustomMappings(DozerBeanMapper.java:213)
    at org.dozer.DozerBeanMapper.initMappings(DozerBeanMapper.java:315)
    at org.dozer.DozerBeanMapper.getMappingProcessor(DozerBeanMapper.java:192)
    at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:120)
    at com.test.dozer.BeanMapper.main(BeanMapper.java:23)

**Comment by garethahealy** [comment]
@bhawnaasnani ; JDK8 is only supported. Can you retest with latest please

**Comment by garethahealy** [comment]
Closing due to inactivity.
