### ISSUE TITLE
Dozer throws NullPointerException when setting value to JAXB Object types with no setter methods

### ISSUE THREAD

**Issue by sbanal** [DozerMapper/dozer#159]
Hi,

I am encountering an issue with Dozer throwing a NullPointerException when a deep copy expression involves setting list values to JAXB Objects. It is triggered due to a missing setter method in the JAXB class generated by xjc whenever a complex type has an XSD definition with multiple valued field. This can actually happen not only on JAXB generated code but also on custom Java bean classes which may have a missing setter method (maybe done intentionally or a defect in the bean code).

There is a way to avoid this issue by forcing xjc to generate setter method for multi-valued fields. But, it would be great if Dozer is able to handle the NullPointerException  and throw a more meaningful exception to developers if this scenario happens. 

Stack trace below:

```
java.lang.NullPointerException
    at org.dozer.util.ReflectionUtils.invoke(ReflectionUtils.java:329)
    at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.writeDeepDestinationValue(GetterSetterPropertyDescriptor.java:232)
    at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.setPropertyValue(GetterSetterPropertyDescriptor.java:96)
    at org.dozer.fieldmap.MapFieldMap.writeDestValue(MapFieldMap.java:84)
    at org.dozer.MappingProcessor.writeDestinationValue(MappingProcessor.java:939)
    at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:368)
    at org.dozer.MappingProcessor.mapField(MappingProcessor.java:307)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:267)
    at org.dozer.MappingProcessor.processSuperTypeMapping(MappingProcessor.java:1067)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:256)
    at org.dozer.MappingProcessor.mapToDestObject(MappingProcessor.java:216)
    at org.dozer.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:196)
    at org.dozer.MappingProcessor.mapGeneral(MappingProcessor.java:170)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:104)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:99)
    at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:120)
    at com.test.MyTestCase.testMap2Obj2(MyTestCase.java:154)
```

**Comment by sbanal** [comment]
Thank you.

**Comment by nine99systems** [comment]
Here is latest dozer's maven repo link : 

https://mvnrepository.com/artifact/net.sf.dozer/dozer/5.5.1

**Comment by garethahealy** [comment]
@sbanal ; is this still an issue? or did #101 fix it?

**Comment by garethahealy** [comment]
Closing due to inactivity.
