### ISSUE TITLE
Dozer OSGI throws class cast exception

### ISSUE THREAD

**Issue by rajeshmeda** [DozerMapper/dozer#168]
When using Dozer as OSGI, it is throwing below exception. The Dozer OSGI bundle is in resolved status but it is not in Active status. Its dependencies org.osgi.core and apache commons lang 3 are in active status.

!ENTRY net.sf.dozer.dozer-osgi 4 0 2014-06-10 11:03:53.505
!MESSAGE 
!STACK 0
org.osgi.framework.BundleException: The activator org.dozer.osgi.Activator for bundle net.sf.dozer.dozer-osgi is invalid
    at org.eclipse.osgi.framework.internal.core.AbstractBundle.loadBundleActivator(AbstractBundle.java:157)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:751)
    at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:352)
    at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:370)
    at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1068)
    at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:557)
    at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:464)
    at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:248)
    at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:445)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:227)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:337)
Caused by: java.lang.ClassCastException: org.dozer.osgi.Activator cannot be cast to org.osgi.framework.BundleActivator
    at org.eclipse.osgi.framework.internal.core.AbstractBundle.loadBundleActivator(AbstractBundle.java:152)
    ... 10 more
Root exception:
java.lang.ClassCastException: org.dozer.osgi.Activator cannot be cast to org.osgi.framework.BundleActivator
    at org.eclipse.osgi.framework.internal.core.AbstractBundle.loadBundleActivator(AbstractBundle.java:152)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:751)
    at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:352)
    at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:370)
    at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1068)
    at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:557)
    at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:464)
    at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:248)
    at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:445)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:227)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:337)

**Comment by garethahealy** [comment]
@rajeshmeda ; is this still a problem?

**Comment by orange-buffalo** [comment]
This was likely caused by the OSGi framework classes bundled into `dozer-osgi` artifact. On `master`, this is fixed - Dozer does not contain framework classes anymore.

**Comment by garethahealy** [comment]
Please re-test with latest - 6.0.0
