### ISSUE TITLE
Map<String, Set<String>> is not mapped correctly

### ISSUE THREAD

**Issue by aduchate** [DozerMapper/dozer#169]
The following code fails with 

```
Exception in thread "main" java.lang.ClassCastException: 
java.util.Collections$SingletonSet cannot be cast to java.util.List
    at org.dozer.MappingProcessor.mapCollection(MappingProcessor.java:574)
    at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:453)
    at org.dozer.MappingProcessor.mapMap(MappingProcessor.java:605)
    at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:414)
    at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:361)
    at org.dozer.MappingProcessor.mapField(MappingProcessor.java:307)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:267)
    at org.dozer.MappingProcessor.mapToDestObject(MappingProcessor.java:216)
    at org.dozer.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:196)
    at org.dozer.MappingProcessor.mapGeneral(MappingProcessor.java:170)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:104)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:99)
    at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:120)
    at Test.main(Test.java:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)'''
```

``` java
public class Test {
    public static class From {
        Map<String,Set<String>> theMap;
        public Map<String, Set<String>> getTheMap() { return theMap; }
        public void setTheMap(Map<String, Set<String>> theMap) { this.theMap = theMap; }
    }

    public static class To {
        Map<String,Set<String>> theMap;
        public Map<String, Set<String>> getTheMap() { return theMap; }
        public void setTheMap(Map<String, Set<String>> theMap) { this.theMap = theMap; }
    }

    public static void main(String[] args) {
        From from = new From();
        from.setTheMap(new HashMap<String, Set<String>>());
        from.getTheMap().put("a", Collections.singleton("b"));

        To to = new DozerBeanMapper().map(from,To.class);
    }
```

**Comment by garethahealy** [comment]
@aduchate ; is this still an issue? if so, can you create a github repo, that includes a unit test showing this behaviour and link it here.

**Comment by garethahealy** [comment]
Closing due to inactivity.
