### ISSUE TITLE
Dozer Field mapping fails when using JUnit

### ISSUE THREAD

**Issue by oliversavio** [DozerMapper/dozer#213]
I get a DestBeanCreator error when running JUnit test.

This fails
<code>
MyObjectDestination destinationObj = null;
<br />
destinationObj = dozerMapper.map(sourceObject, MyObjectDestination.class);
</code>

This works
<code>
MyObjectDestination destinationObj = new MyObjectDestination(); 
<br />
dozerMapper.map(sourceObject, destinationObj);
</code>

<br />
Stackstace
<code>
java.lang.NoClassDefFoundError: Could not initialize class org.dozer.factory.DestBeanCreator
    at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.writeDeepDestinationValue(GetterSetterPropertyDescriptor.java:186)
    at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.setPropertyValue(GetterSetterPropertyDescriptor.java:96)
    at org.dozer.fieldmap.FieldMap.writeDestValue(FieldMap.java:96)
    at org.dozer.MappingProcessor.writeDestinationValue(MappingProcessor.java:939)
    at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:368)
    at org.dozer.MappingProcessor.mapField(MappingProcessor.java:307)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:267)
    at org.dozer.MappingProcessor.mapToDestObject(MappingProcessor.java:216)
    at org.dozer.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:202)
    at org.dozer.MappingProcessor.mapGeneral(MappingProcessor.java:170)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:113)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:108)
    at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:127)
</code>
The same code works perfectly when running as part of the web app.

**Comment by garethahealy** [comment]
@oliversavio ; is this still an issue? if so, can you create a github repo, that includes a unit test showing this behaviour and link it here.

**Comment by garethahealy** [comment]
Closing due to inactivity.
