### ISSUE TITLE
ClassCastException on "chained generics"

### ISSUE THREAD

**Issue by ledben** [DozerMapper/dozer#229]
Here is the issue I meet when trying to map my domain model.
I have a class Bean that handles Attributes. These Attributes are templated. So we have a chained generics `List<Attribute<?>>` : 

``` java
public class Bean {
    private List<Attribute<?>> attributes = new ArrayList<>();

    public List<Attribute<?>> getAttributes() {
        return attributes;
    }

    public void setAttributes(List<Attribute<?>> attributes) {
        this.attributes = attributes;
    }
}

public class Attribute<T> {
    private T value;

    public Attribute() {
    }

    public Attribute(T value) {
        this.value = value;
    }

    public T getValue() {
        return value;
    }

    public void setValue(T value) {
        this.value = value;
    }
}
```

When I try to map the bean : 

``` java
public class BeanTest {

    @Test
    public void testMapp() {

        DozerBeanMapper mapper = new DozerBeanMapper();

        Bean bean = new Bean();

        bean.getAttributes().add(new Attribute<String>("Je suis charlie"));

        Bean mappedBean = mapper.map(bean, Bean.class);

        Object value = mappedBean.getAttributes().get(0).getValue();
        Assert.assertEquals("Je suis charlie", value);
    }
}
```

... I get the following Exception : 

``` java
Exception in thread "main" java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
    at org.dozer.util.ReflectionUtils.determineGenericsType(ReflectionUtils.java:416)
    at org.dozer.util.ReflectionUtils.determineGenericsType(ReflectionUtils.java:395)
    at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.genericType(GetterSetterPropertyDescriptor.java:363)
    at org.dozer.fieldmap.FieldMap.getGenericType(FieldMap.java:141)
    at org.dozer.MappingProcessor.mapCollection(MappingProcessor.java:525)
    at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:453)
    at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:361)
    at org.dozer.MappingProcessor.mapField(MappingProcessor.java:307)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:267)
    at org.dozer.MappingProcessor.mapToDestObject(MappingProcessor.java:216)
    at org.dozer.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:196)
    at org.dozer.MappingProcessor.mapGeneral(MappingProcessor.java:170)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:104)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:99)
    at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:120)
    at com.ben.test.Main.main(Main.java:15)
```

The issue come from the method `ReflectionUtils.determineGenericsType(Type type)` : 

``` java
  public static Class<?> determineGenericsType(Type type) {
    Class<?> result = null;
    if (type != null && ParameterizedType.class.isAssignableFrom(type.getClass())) {
      Type genericType = ((ParameterizedType) type).getActualTypeArguments()[0];
      if (genericType != null) {
         if(! (genericType instanceof TypeVariable)) {
            result = (Class<?>) genericType;//Here is the ClassCastException
         }
      }
    }
    return result;
  }
```

One can fix it with the following method : 

``` java

    public static Class<?> determineGenericsType(Type type) {
        Class<?> result = null;
        if (type != null && ParameterizedType.class.isAssignableFrom(type.getClass())) {
            Type genericType = ((ParameterizedType) type).getActualTypeArguments()[0];
            if (genericType != null) {
                if (genericType instanceof Class) {
                    result = (Class<?>) genericType;
                }
                else if (genericType instanceof ParameterizedType) {
                    Type rawType = ((ParameterizedType) genericType).getRawType();
                    result = (Class<?>) rawType;
                }
            }
        }
        return result;
    }
```

I don't know if this the relevant fix, but it fixes my issue.

**Comment by sventschui** [comment]
Same for me. When will this be fixed?

**Comment by cash1981** [comment]
We hit the same problem.
Would be nice with a fix!
