### ISSUE TITLE
java.util.ConcurrentModificationException when I process many objects

### ISSUE THREAD

**Issue by ghwrivas** [DozerMapper/dozer#237]
One process works fine but when I process many objects, is not working

Java 1.7
Windows 7 64 bits
AppEngine Dev 1.9.10
Pom config:

<pre>
        <dependency>
            <groupId>net.sf.dozer</groupId>
            <artifactId>dozer</artifactId>
            <version>5.5.1</version>
        </dependency>
</pre>

Mapping config file:
<code>
    <mapping relationship-type="non-cumulative">
        <class-a>com.example.Object</class-a>
        <class-b>com.example.Object</class-b>
        <field-exclude>
            <a>usuario</a>
            <b>usuario</b>
        </field-exclude>
        <field-exclude>
            <a>id</a>
            <b>id</b>
        </field-exclude>
        
        <field  remove-orphans="true" relationship-type="non-cumulative">
            <a>telefonos</a>
            <b>telefonos</b>
        </field>
        
        <field remove-orphans="true" relationship-type="non-cumulative">
            <a>direcciones</a>
            <b>direcciones</b>
        </field>
    </mapping>
</code>

Spring config:

<pre>
    @Bean(name = "dozerBeanMapper")
    public DozerBeanMapper dozerBeanMapper(){
        DozerBeanMapper dozer = new DozerBeanMapper();
        List<String> mappingFiles = new ArrayList<String>();
        mappingFiles.add("mapping.xml");
        dozer.setMappingFiles(mappingFiles);
        return dozer;
    }
</pre>

Exceptions when I am trying to process many objects on data migration:

<pre>
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
    at java.util.ArrayList$Itr.next(ArrayList.java:831)
    at org.dozer.MappingProcessor.addOrUpdateToList(MappingProcessor.java:810)
    at org.dozer.MappingProcessor.addOrUpdateToList(MappingProcessor.java:894)
    at org.dozer.MappingProcessor.mapListToList(MappingProcessor.java:730)
    at org.dozer.MappingProcessor.mapCollection(MappingProcessor.java:580)
    at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:453)
    at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:361)
    at org.dozer.MappingProcessor.mapField(MappingProcessor.java:307)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:267)
    at org.dozer.MappingProcessor.mapToDestObject(MappingProcessor.java:216)
    at org.dozer.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:202)
    at org.dozer.MappingProcessor.mapGeneral(MappingProcessor.java:170)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:113)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:108)
    at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:127)
</pre>

**Comment by garethahealy** [comment]
@ghwrivas  ; is this still an issue? if so, can you create a github repo, that includes a unit test showing this behaviour and link it here.

**Comment by garethahealy** [comment]
Closing due to inactivity.

**Comment by ParasMittal** [comment]
@ghwrivas Did you get to know any workaround on this issue? I am facing the same issue. Any lead any lead will be really appreciated.
