### ISSUE TITLE
ClassNotFoundException since upgrade hibernate-validator library version

### ISSUE THREAD

**Issue by kristoflarcher** [DozerMapper/dozer#245]
```
Hi,
```

My name is Christophe from France.
I decided to upgrade  2 libraries in the pom of my project ( for the bean validation) :                        hibernate-validator-4.2.0 -->  hibernate-validator-5.1.3.Final  and
     validation-api-1.0.0.GA   --->  validation-api-1.1.0.Final           

And now I have an exception thrown  in my Spring MvcController when I try  to use dozer-mapper :: 
StackTrace
11:40:17.280 [my-thread-5] ERROR o.d.loader.xml.MappingStreamReader - Error while loading dozer mapping InputStream: [java.io.BufferedInputStream@b6724b1]
org.dozer.MappingException: java.lang.ClassNotFoundException: org.hibernate.validator.engine.ConstraintViolationImpl
    at org.dozer.util.MappingUtils.throwMappingException(MappingUtils.java:82) ~[dozer-5.5.1.jar:na]
    at org.dozer.util.DefaultClassLoader.loadClass(DefaultClassLoader.java:43) 

I don't know why this classNotFoundException is thrown : this class  is in the classpath.
So I would like to know why there is a problem whith the DefaultClassLoader used by dozer

Best regards.
Christophe

**Comment by garethahealy** [comment]
@kristoflarcher ; is this still an issue? if so, can you create a github repo, that includes a unit test showing this behaviour and link it here.

**Comment by garethahealy** [comment]
Closing due to inactivity.
