### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by damien-raemy** [DozerMapper/dozer#252]
Hello,

Is there a supported version for Android use? I tryed dozer in Android but I have the following error: 

```
 java.lang.IllegalArgumentException: http://apache.org/xml/features/validation/schema
 at org.apache.harmony.xml.parsers.DocumentBuilderFactoryImpl.setAttribute(DocumentBuilderFactoryImpl.java:86)
at org.dozer.loader.xml.XMLParserFactory.createDocumentBuilderFactory(XMLParserFactory.java:56)
at org.dozer.loader.xml.XMLParserFactory.createParser(XMLParserFactory.java:35)
at org.dozer.loader.xml.MappingStreamReader.<init>(MappingStreamReader.java:43)
at org.dozer.loader.xml.MappingFileReader.<init>(MappingFileReader.java:44)
at org.dozer.DozerBeanMapper.loadFromFiles(DozerBeanMapper.java:219)
at org.dozer.DozerBeanMapper.loadCustomMappings(DozerBeanMapper.java:209)
at org.dozer.DozerBeanMapper.initMappings(DozerBeanMapper.java:315)
at org.dozer.DozerBeanMapper.getMappingProcessor(DozerBeanMapper.java:192)
at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:120)
```

I think it's a XML configuration file problem.

**Comment by laoyur** [comment]
Hi, am facing the same problem
Could you add Android support ?

**Comment by damien-raemy** [comment]
Hi,

Unfortunatly not. I could do the mapping by hand because it was a small project but it can become difficult for bigger ones.

I think that it should not take too many time to write a little mapper yourself using reflexion.

**Comment by garethahealy** [comment]
@damien-raemy / @laoyur ; Android support is not a simple task. If someone wants to do the work, happy for PRs to be raised, but for now, closing issue.
