### ISSUE TITLE
Dozer stops working somtimes with  "Field mapping error" due to "Exception occurred determining deep field hierarchy for Class ... Unable to determine property descriptor for Class"

### ISSUE THREAD

**Issue by elonderin** [DozerMapper/dozer#269]
this might be related to #118 / #160 and yet might not be, which is why i open a new bug.
we are still using dozer 5.4.0. at the time and jdk 1.7.72
we have this problem since end of 2014.

the exception text is this:

```
2015-10-28 08:36:27,436 ERROR org.dozer.MappingProcessor:295 - Field mapping error -->
  MapId: null
  Type: null
  Source parent class: de.tomsit.dozer.fieldmappingbug.entities.PartGroupPart
  Source field name: pk.partNumber
  Source field type: null
  Source field value: null
  Dest parent class: de.tomsit.dozer.fieldmappingbug.ui.PartGroupPartVO
  Dest field name: partNumber
  Dest field type: my.project.model.common.PartNumber
org.dozer.MappingException: Exception occurred determining deep field hierarchy for Class 
    --> de.tomsit.dozer.fieldmappingbug.entities.PartGroupPart, Field --> pk.partNumber.  
    Unable to determine property descriptor for Class 
     --> java.io.Serializable, Field Name: partNumber   
 at org.dozer.util.MappingUtils.throwMappingException(MappingUtils.java:87) 
 at org.dozer.util.ReflectionUtils.getDeepFieldHierarchy(ReflectionUtils.java:149)  
 at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.getDeepFieldHierarchy(GetterSetterPropertyDescriptor.java:285)  
 at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.getDeepSrcFieldValue(GetterSetterPropertyDescriptor.java:112)   
 ...
```

this occurs every once and a while and with different classes and i know of now way to reproduce it, but the message pattern is always the same.
in the past that happened only on our QS and TEST systems but now it occurred in production which is really bad and which is why i post it here now.
we also have noticed that problem quite often during development when the debugger reloaded the web app. 

since the classes have some hierarchy to them, which is cumbersome to explain, i pushed a stripped down version of the code to https://bitbucket.org/elonderin/dozer-field-mapping-error.git

this is what i gathered so far:
it seems that at some point in time dozer loses the reflection info on the types or rather it doesnt get the right type. 
in this case pk is determined as being Serializable which is true as it extends the interface but obviously it lacks the property partNumber.  

i have tried to find similar bugs and have only found #118 and #160 which come closest in regard to appearing at some time and where i have read the idea about a problem with garbage collection, which i think is here the case too, due to these facts:
1. in the past this problem only occurred on the not-so-much-used TEST and QS environments.
2. bug BEANUTILS-456, but not sure if 100% applicable
3. since we had no clue what to do, we tried out diff. stuff and also thought that hints might help here. so we added a few and the problem seemed to be gone but now they are back.
when i revisited the code i noticed that we might have used the wrong hints (deep index, and they are commented out now) and and are ignored anyhow because of copy-by-reference="true". however, it might be that the hint objects affect the garbage collection positively.

any ideas?

heaving reread #118 and seen the newer posts i will try the following on our end:
- remove all the (unneeded) hints
- update to dozer 5.5.1
- maybe even to the current trunk as 5.5.2 is not out yet, but that will need some convincing of the application support

PS: a bit more clear doc on the hints would have been helpful since i still dont know if and how they can help here at all, although i have read that u can/should/must use them in connection to interfaces

**Comment by elonderin** [comment]
as far as reproducing goes: i just tried the following:

i set a break point in the test class on line 26 which is when i do the 2nd/reverse mapping.
the i opened the display view in eclipse and called <System.gc();> and voi la, i got it to fail with:

````
org.dozer.MappingException: Exception occurred determining deep field hierarchy for Class --> de.tomsit.dozer.fieldmappingbug.entities.PartGroupPart, Field --> pk.partNumber.  Unable to determine property descriptor for Class --> java.io.Serializable, Field Name: partNumber
	at org.dozer.util.MappingUtils.throwMappingException(MappingUtils.java:87)
	at org.dozer.util.ReflectionUtils.getDeepFieldHierarchy(ReflectionUtils.java:149)
	at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.getDeepFieldHierarchy(GetterSetterPropertyDescriptor.java:285)
	at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.writeDeepDestinationValue(GetterSetterPropertyDescriptor.java:140)
	at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.setPropertyValue(GetterSetterPropertyDescriptor.java:87)
	at org.dozer.fieldmap.FieldMap.writeDestValue(FieldMap.java:94)
	at org.dozer.MappingProcessor.writeDestinationValue(MappingProcessor.java:895)
	at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:349)
	at org.dozer.MappingProcessor.mapField(MappingProcessor.java:288)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:248)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:197)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:187)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:124)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:119)
	at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:120)
	at de.tomsit.dozer.fieldmappingbug.entities.PartGroupPartVOTest.test2Vo(PartGroupPartVOTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
````
but i was only the 1st time successful and cannot repro it anymore that way

**Comment by garethahealy** [comment]
@elonderin ; is this still an issue? if so, can you create a github repo, that includes a unit test showing this behaviour and link it here.

NOTE: JDK7 support is dropped going forward, so please retest with JDK8 and latest code.

**Comment by garethahealy** [comment]
Closing due to inactivity.
