### ISSUE TITLE
Handling InterruptedExceptions coming from DozerBeanMapper.initMappings

### ISSUE THREAD

**Issue by jeffc-mirth** [DozerMapper/dozer#277]
Hi there,

My company's application uses DozerBeanMapper for mapping objects like this:

```
public <I, O> void map(I source, O destination) throws MappingException {
    if (source == null) {
        return;
    }
    mapper.map(source, destination);
}
```

This works fine for the most part, but sometimes, possibly when the application is under load, we'll see a ton of InterruptedExceptions coming from DozerBeanMapper.initMappings:

```
[#|2015-12-09T17:18:14.709-0500|SEVERE|glassfish3.1.2|org.dozer.DozerBeanMapper|_ThreadID=385;_ThreadName=Thread-7;|Thread interrupted: 
java.lang.InterruptedException
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1301)
    at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:236)
    at org.dozer.DozerBeanMapper.initMappings(DozerBeanMapper.java:327)
    at org.dozer.DozerBeanMapper.getMappingProcessor(DozerBeanMapper.java:192)
    at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:127)
    at com.mirth.commons.objectmapping.Mapper.map(Mapper.java:47)
```

What's the best way to handle these? Should we check if the thread has been interrupted in our map method and throw an exception if so? Something like this?

```
public <I, O> void map(I source, O destination) throws MappingException {
    if (source == null) {
        return;
    }
    mapper.map(source, destination);

    if (Thread.currentThread().isInterrupted()) {
        throw new RuntimeException("Dozer was interrupted, canceling request");
    }
}
```

**Comment by garethahealy** [comment]
- https://docs.oracle.com/javase/8/docs/api/java/lang/InterruptedException.html

**Comment by garethahealy** [comment]
Closing as 'initMappings' code path doesnt exist anymore. If you still have problem with latest version 6.4.1, please open a new ticket with info.
