### ISSUE TITLE
WildcardTypeImpl cannot be cast to java.lang.Class

### ISSUE THREAD

**Issue by dhanaraj** [DozerMapper/dozer#292]
java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.WildcardTypeImpl cannot be cast to java.lang.Class
    at org.dozer.util.ReflectionUtils.determineGenericsType(ReflectionUtils.java:416)
    at org.dozer.util.ReflectionUtils.determineGenericsType(ReflectionUtils.java:395)
    at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.genericType(GetterSetterPropertyDescriptor.java:363)
    at org.dozer.fieldmap.FieldMap.getGenericType(FieldMap.java:141)
    at org.dozer.MappingProcessor.mapCollection(MappingProcessor.java:525)
    at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:453)
    at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:361)
    at org.dozer.MappingProcessor.mapField(MappingProcessor.java:307)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:267)
    at org.dozer.MappingProcessor.mapToDestObject(MappingProcessor.java:216)
    at org.dozer.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:196)
    at org.dozer.MappingProcessor.mapCustomObject(MappingProcessor.java:512)
    at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:465)
    at org.dozer.MappingProcessor.addOrUpdateToList(MappingProcessor.java:820)
    at org.dozer.MappingProcessor.addOrUpdateToList(MappingProcessor.java:894)
    at org.dozer.MappingProcessor.mapListToList(MappingProcessor.java:730)
    at org.dozer.MappingProcessor.mapCollection(MappingProcessor.java:580)
    at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:453)
    at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:361)
    at org.dozer.MappingProcessor.mapField(MappingProcessor.java:307)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:267)
    at org.dozer.MappingProcessor.mapToDestObject(MappingProcessor.java:216)
    at org.dozer.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:196)
    at org.dozer.MappingProcessor.mapCustomObject(MappingProcessor.java:512)
    at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:465)
    at org.dozer.MappingProcessor.addToSet(MappingProcessor.java:757)
    at org.dozer.MappingProcessor.mapCollection(MappingProcessor.java:570)
    at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:453)
    at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:361)
    at org.dozer.MappingProcessor.mapField(MappingProcessor.java:307)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:267)
    at org.dozer.MappingProcessor.mapToDestObject(MappingProcessor.java:216)
    at org.dozer.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:196)
    at org.dozer.MappingProcessor.mapCustomObject(MappingProcessor.java:512)
    at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:465)
    at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:361)
    at org.dozer.MappingProcessor.mapField(MappingProcessor.java:307)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:267)
    at org.dozer.MappingProcessor.mapToDestObject(MappingProcessor.java:216)
    at org.dozer.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:196)
    at org.dozer.MappingProcessor.mapGeneral(MappingProcessor.java:170)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:104)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:99)
    at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:120)

**Comment by dhanaraj** [comment]
Its is reproducible in the latest version of dozer-5.5.1.jar

**Comment by dhanaraj** [comment]
public interface SomeInterface {
 public void setChildren(List <? extends SomeInterface>);
 public  List <? extends SomeInterface> getChildren();
}

public class SomeType implements SomeInterface {
  private List<SomeType > children;
  public setChildren(List <? extends SomeInterface> 
   ...  
   }
}
  

When this "SomeType" is mapped by dozer it fails with java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.WildcardTypeImpl cannot be cast to java.lang.Class

**Comment by garethahealy** [comment]
@dhanaraj ; is this still an issue? if so, can you create a github repo, that includes a unit test showing this behaviour and link it here.

**Comment by garethahealy** [comment]
Closing due to inactivity.
