### ISSUE TITLE
Mention update of xsd location in Migration guide 5.5.1 to 6.0

### ISSUE THREAD

**Issue by apupier** [DozerMapper/dozer#536]
in https://github.com/DozerMapper/dozer/blob/master/docs/asciidoc/migration/v5-to-v6.adoc there is no mention that the xsd location need to be updated but at runtime there is this error:

```
org.dozer.MappingException: Dozer >= v6.0.0 uses a new XSD location. Your current config needs to be upgraded. Found v5 XSD: 'http://dozer.sourceforge.net/schema/beanmapping.xsd'. Expected v6 XSD: 'http://dozermapper.github.io/schema/bean-mapping.xsd'. Please see migration guide @ https://dozermapper.github.io/gitbook
	at org.dozer.loader.xml.DozerResolver.resolveEntity(DozerResolver.java:60)
	at com.sun.org.apache.xerces.internal.util.EntityResolverWrapper.resolveEntity(EntityResolverWrapper.java:110)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.resolveEntity(XMLEntityManager.java:1081)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.resolveDocument(XMLSchemaLoader.java:657)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.findSchemaGrammar(XMLSchemaValidator.java:2430)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1767)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:740)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3132)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:852)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at org.dozer.loader.xml.MappingStreamReader.read(MappingStreamReader.java:52)
	at org.dozer.loader.xml.MappingFileReader.read(MappingFileReader.java:60)
	at org.dozer.DozerBeanMapper.loadFromFiles(DozerBeanMapper.java:340)
	at org.dozer.DozerBeanMapper.loadCustomMappings(DozerBeanMapper.java:322)
	at org.dozer.DozerBeanMapper.initMappings(DozerBeanMapper.java:443)
	at org.dozer.DozerBeanMapper.getMappingMetadata(DozerBeanMapper.java:416)
```

**Comment by garethahealy** [comment]
@apupier ; 6.0.0 does not include this change, so not sure how you are getting that error. v6.1 does
- https://github.com/DozerMapper/dozer/blob/v6.0.0/core/src/main/java/org/dozer/loader/xml/DozerResolver.java

- https://github.com/DozerMapper/dozer/blob/6.1.0/core/src/main/java/org/dozer/loader/xml/DozerResolver.java
- https://github.com/DozerMapper/dozer/blob/master/docs/asciidoc/migration/v6-to-v61.adoc

**Comment by apupier** [comment]
my bad, I have transitive dependency to Dozer only. I didn't took care that it was 6.1 and not 6.0.
Thanks for the pointers
