### ISSUE TITLE
Error trying to map between classes with byte[][] fields

### ISSUE THREAD

**Issue by starikoff** [DozerMapper/dozer#544]
## Whats your runtime?
* Dozer version: 5.5.1
* OS version: Win7
* JDK version: 1.8.0_111
  
## Whats the problem?
1. Try to map an object of a class having a byte[][] field to another class (or the same, actually) having a byte[][] field; field names being the same.
  
### Observed Results:
An exception is thrown and an error log entry is written:
```
[main] ERROR org.dozer.MappingProcessor - Field mapping error -->
  MapId: null
  Type: null
  Source parent class: ru.ra.Src
  Source field name: columns
  Source field type: class [[B
  Source field value: [[B@b97c004
  Dest parent class: ru.ra.Dst
  Dest field name: columns
  Dest field type: [[B
java.lang.IllegalArgumentException: array element type mismatch
	at java.lang.reflect.Array.set(Native Method)
	at org.dozer.MappingProcessor.addToPrimitiveArray(MappingProcessor.java:712)
	at org.dozer.MappingProcessor.mapArrayToArray(MappingProcessor.java:629)
	at org.dozer.MappingProcessor.mapCollection(MappingProcessor.java:551)
	at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:453)
	at org.dozer.MappingProcessor.addOrUpdateToList(MappingProcessor.java:820)
	at org.dozer.MappingProcessor.mapArrayToArray(MappingProcessor.java:634)
	at org.dozer.MappingProcessor.mapCollection(MappingProcessor.java:551)
	at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:453)
	at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:361)
	at org.dozer.MappingProcessor.mapField(MappingProcessor.java:307)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:267)
	at org.dozer.MappingProcessor.mapToDestObject(MappingProcessor.java:216)
	at org.dozer.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:196)
	at org.dozer.MappingProcessor.mapGeneral(MappingProcessor.java:170)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:104)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:99)
	at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:120)
	at ru.ra.DozerTest.testApp(DozerTest.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```
### Expected Results:
Mapping succeeds.

## Link to GitHub repo with Unit test
https://github.com/starikoff/Dozer2DArrayBug.git
clone and "mvn test"

Likely the same for other types of 2d-arrays and other dimensionalities bigger than 1.

**Comment by starikoff** [comment]
This patch fixes this particular test for me, but it looks like every usage of FieldMap in collection-mapping and array-mapping methods in MappingProcessor should be removed too (changed to something else) in order for nested collections and/or arrays to work.
```
diff --git a/core/src/main/java/org/dozer/MappingProcessor.java b/core/src/main/java/org/dozer/MappingProcessor.java
index 36fe713..6c6ab24 100644
--- a/core/src/main/java/org/dozer/MappingProcessor.java
+++ b/core/src/main/java/org/dozer/MappingProcessor.java
@@ -494,7 +494,7 @@ public class MappingProcessor implements Mapper {
       }
     }
     if (MappingUtils.isSupportedCollection(srcFieldClass) && (MappingUtils.isSupportedCollection(destFieldType))) {
-      return mapCollection(srcObj, srcFieldValue, fieldMap, destObj);
+      return mapCollection(srcObj, srcFieldValue, fieldMap, destObj, destFieldType);
     }
 
     if (MappingUtils.isEnumType(srcFieldClass, destFieldType)) {
@@ -562,7 +562,7 @@ public class MappingProcessor implements Mapper {
     return result;
   }
 
-  private Object mapCollection(Object srcObj, Object srcCollectionValue, FieldMap fieldMap, Object destObj) {
+  private Object mapCollection(Object srcObj, Object srcCollectionValue, FieldMap fieldMap, Object destObj, Class destCollectionType) {
     // since we are mapping some sort of collection now is a good time to decide
     // if they provided hints
     // if no hint is provided then we will use generics to determine the mapping type
@@ -582,7 +582,7 @@ public class MappingProcessor implements Mapper {
       srcCollectionValue = IteratorUtils.toList((Iterator<?>) srcCollectionValue);
     }
 
-    Class<?> destCollectionType = fieldMap.getDestFieldType(BuilderUtil.unwrapDestClassFromBuilder(destObj));
+//    Class<?> destCollectionType = fieldMap.getDestFieldType(BuilderUtil.unwrapDestClassFromBuilder(destObj));
     Class<?> srcFieldType = srcCollectionValue.getClass();
     Object result = null;
 
@@ -597,7 +597,8 @@ public class MappingProcessor implements Mapper {
     }
     // Array to Array
     if (CollectionUtils.isArray(srcFieldType) && (CollectionUtils.isArray(destCollectionType))) {
-      result = mapArrayToArray(srcObj, srcCollectionValue, fieldMap, destObj);
+      Class<?> destEntryType = destCollectionType.getComponentType();
+      result = mapArrayToArray(srcObj, srcCollectionValue, fieldMap, destObj, destEntryType);
     } else if (CollectionUtils.isArray(srcFieldType) && (CollectionUtils.isList(destCollectionType))) {
       // Array to List
       result = mapArrayToList(srcObj, srcCollectionValue, fieldMap, destObj);
@@ -656,11 +657,11 @@ public class MappingProcessor implements Mapper {
     return result;
   }
 
-  private Object mapArrayToArray(Object srcObj, Object srcCollectionValue, FieldMap fieldMap, Object destObj) {
-    Class destEntryType = fieldMap.getDestFieldType(destObj.getClass()).getComponentType();
+  private Object mapArrayToArray(Object srcObj, Object srcCollectionValue, FieldMap fieldMap, Object destObj, Class destEntryType) {
+//    Class destEntryType = fieldMap.getDestFieldType(destObj.getClass()).getComponentType();
     Class srcEntryType = srcCollectionValue.getClass().getComponentType();
     int size = Array.getLength(srcCollectionValue);
-    
+
     CopyByReferenceContainer copyByReferences = globalConfiguration.getCopyByReferences();
     boolean isPrimitiveArray = CollectionUtils.isPrimitiveArray(srcCollectionValue.getClass());
     boolean isFinal = Modifier.isFinal(srcEntryType.getModifiers());
@@ -713,7 +714,7 @@ public class MappingProcessor implements Mapper {
           fieldMapping.getDestFieldName(), srcFieldValue, null, fieldMapping.getClassMap().getMapId()));
     }
   }
-  
+
   private Object addArrayContentCopy(FieldMap fieldMap, int size, Object srcCollectionValue, Object destObj,
           Class destEntryType) {
       Object result;
```
