### ISSUE TITLE
`ReflectionUtil.findNonSyntheticMethod` failing for non-generics methods

### ISSUE THREAD

**Issue by mateusz-bajorek** [DozerMapper/dozer#550]
## Whats your runtime?
* Dozer version: 6.1.0
* OS version: CentOS 6.5 / Mac OS High Sierra
* JDK version: 1.8u131
  
## Whats the problem?
`ReflectionUtil.findNonSyntheticMethod` is failing (resulting in `null` return value) in valid scenario.

### Observed Results:
[PageImpl](https://github.com/spring-projects/spring-data-commons/blob/1.13.x/src/main/java/org/springframework/data/domain/PageImpl.java) is a Spring Data class representing a paged collection from DB. It extends [Chunk](https://github.com/spring-projects/spring-data-commons/blob/1.13.x/src/main/java/org/springframework/data/domain/Chunk.java) which in turn implements [Slice](https://github.com/spring-projects/spring-data-commons/blob/1.13.x/src/main/java/org/springframework/data/domain/Slice.java).

I try to map [`Page<MyEntity>`](https://github.com/spring-projects/spring-data-commons/blob/1.13.x/src/main/java/org/springframework/data/domain/Page.java) to a DTO and get this error during mapping:
```
Caused by: java.lang.NoSuchMethodException: Unable to determine read method for Field: 'number' in Class: class org.springframework.data.domain.PageImpl
	at org.dozer.propertydescriptor.JavaBeanPropertyDescriptor.retryMissingMethod(JavaBeanPropertyDescriptor.java:94) ~[dozer-core-6.1.0.jar:6.1.0]
	at org.dozer.propertydescriptor.JavaBeanPropertyDescriptor.getReadMethod(JavaBeanPropertyDescriptor.java:68) ~[dozer-core-6.1.0.jar:6.1.0]
	at org.dozer.propertydescriptor.JavaBeanPropertyDescriptor.retryMissingMethod(JavaBeanPropertyDescriptor.java:99) ~[dozer-core-6.1.0.jar:6.1.0]
	at org.dozer.propertydescriptor.JavaBeanPropertyDescriptor.getReadMethod(JavaBeanPropertyDescriptor.java:68) ~[dozer-core-6.1.0.jar:6.1.0]
	at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.invokeReadMethod(GetterSetterPropertyDescriptor.java:284) ~[dozer-core-6.1.0.jar:6.1.0]
```
After extensive debugging I found that because `!method.isBridge()` and `!method.isSynthetic()` are returning `false` in the `if` condition, the `ReflectionUtil.findNonSyntheticMethod` method returns `null` for get method.

I found this part was introduced in the following PR: https://github.com/DozerMapper/dozer/pull/4/
  
### Expected Results:
I should get the `Method` for `getNumber` and `setNumber` and, in the end, a correct `PropertyDescriptor` in [ReflectionUtils.java#L117](https://github.com/DozerMapper/dozer/blob/master/core/src/main/java/org/dozer/util/ReflectionUtils.java#L117)

## Link to GitHub repo with Unit test
https://github.com/mateusz-bajorek/dozer-test
You can run the test with `./mvnw test`. It will fail with the exception above.

**Comment by grubeninspekteur** [comment]
Classmate can't help since PageImpl is generic as well, in which case it only returns the upper bound (Object). I tried the linked test with Dozer updated to 6.2.0. The problem here is that the getter is marked as a synthetic bridge, but (probably due to the superclass being abstract) there is no non-synthetic equivalent.

Raised PR #653.
