### ISSUE TITLE
ProtoBeansMappingTest logging exception in tests

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#599]
[main] ERROR com.github.dozermapper.core.MappingProcessor - Field mapping error -->
  MapId: null
  Type: null
  Source parent class: com.github.dozermapper.protobuf.vo.proto.MapExample
  Source field name: value
  Source field type: class java.util.HashMap
  Source field value: {test=null, foo=bar}
  Dest parent class: com.github.dozermapper.protobuf.builder.ProtoBeanBuilder
  Dest field name: value
  Dest field type: null
com.github.dozermapper.core.MappingException: Could not call map setter method putAllValue
	at com.github.dozermapper.protobuf.propertydescriptor.ProtoFieldPropertyDescriptor.setPropertyValue(ProtoFieldPropertyDescriptor.java:163)
	at com.github.dozermapper.core.fieldmap.FieldMap.writeDestValue(FieldMap.java:99)
	at com.github.dozermapper.core.MappingProcessor.writeDestinationValue(MappingProcessor.java:1001)
	at com.github.dozermapper.core.MappingProcessor.mapFromFieldMap(MappingProcessor.java:412)
	at com.github.dozermapper.core.MappingProcessor.mapField(MappingProcessor.java:355)
	at com.github.dozermapper.core.MappingProcessor.map(MappingProcessor.java:315)
	at com.github.dozermapper.core.MappingProcessor.mapToDestObject(MappingProcessor.java:264)
	at com.github.dozermapper.core.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:239)
	at com.github.dozermapper.core.MappingProcessor.mapGeneral(MappingProcessor.java:210)
	at com.github.dozermapper.core.MappingProcessor.map(MappingProcessor.java:134)
	at com.github.dozermapper.core.MappingProcessor.map(MappingProcessor.java:129)
	at com.github.dozermapper.core.DozerBeanMapper.map(DozerBeanMapper.java:136)
	at com.github.dozermapper.protobuf.functional_tests.ProtoBeansMappingTest.testBadMapToProto(ProtoBeansMappingTest.java:266)

**Comment by garethahealy** [comment]
Need to improve ExpectedException logic.

**Comment by garethahealy** [comment]
Related:
- https://github.com/DozerMapper/dozer/issues/598
