### ISSUE TITLE
No internet env fails

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#600]
```
[ERROR] canLoadStreams(com.github.dozermapper.core.builder.xml.BeanMappingXMLBuilderTest)  Time elapsed: 0.291 s  <<< ERROR!
com.github.dozermapper.core.MappingException: java.net.UnknownHostException: dozermapper.github.io
	at com.github.dozermapper.core.builder.xml.BeanMappingXMLBuilderTest.canLoadStreams(BeanMappingXMLBuilderTest.java:50)
Caused by: java.net.UnknownHostException: dozermapper.github.io
	at com.github.dozermapper.core.builder.xml.BeanMappingXMLBuilderTest.canLoadStreams(BeanMappingXMLBuilderTest.java:50)
```

**Comment by garethahealy** [comment]
If in a no-internet env (i.e.: corp network) - might get issues
