### ISSUE TITLE
Fix mapCollection in MappingProcessor

### ISSUE THREAD

**Issue by dmni1905** [DozerMapper/dozer#640]
Can you check mapCollection methot in MappingProcessor.java?
MappingProcessor.java:635-637:

```
if (CollectionUtils.isCollection(srcFieldType) && MappingUtils.isSupportedMap(destCollectionType)) {
            result = mapListToList(srcObj, (List<?>)srcCollectionValue, fieldMap, destObj);
}
```

why you cast Collection to List? if "CollectionUtils.isCollection(srcFieldType)" and mapListToList signature is "mapListToList(Object srcObj, Collection<?> srcCollectionValue, FieldMap fieldMap, Object destObj)"

**Comment by garethahealy** [comment]
@dmni1905 ; are you hitting a bug? if so, can you show the problem via a unit test please. create a github repo with an example and link it here.

**Comment by dmni1905** [comment]
It's bug

Dozer version: 5.5.1
JDK version: 1.8
Unit Test: https://github.com/dmni1905/DozerMapperTest/blob/master/src/test/java/DozerMapTest.java
Error:
```
java.lang.ClassCastException: java.util.HashSet cannot be cast to java.util.List
at org.dozer.MappingProcessor.mapCollection(MappingProcessor.java:574)
at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:453)
at org.dozer.MappingProcessor.mapMap(MappingProcessor.java:605)
at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:414)
at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:361)
at org.dozer.MappingProcessor.mapField(MappingProcessor.java:307)
at org.dozer.MappingProcessor.map(MappingProcessor.java:267)
at org.dozer.MappingProcessor.mapToDestObject(MappingProcessor.java:216)
at org.dozer.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:196)
at org.dozer.MappingProcessor.mapGeneral(MappingProcessor.java:170)
at org.dozer.MappingProcessor.map(MappingProcessor.java:104)
at org.dozer.MappingProcessor.map(MappingProcessor.java:99)
at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:120)
at DozerMapTest.test(DozerMapTest.java:41)
```
