### ISSUE TITLE
LogFactory not found when define only dozer-core

### ISSUE THREAD

**Issue by kazuki43zoo** [DozerMapper/dozer#666]
## Whats your runtime?
* Dozer version: 6.2.0
  
## Whats the problem?
1. Define only `dozer-core` in my pom.xml

```xml
<dependency>
    <groupId>com.github.dozermapper</groupId>
    <artifactId>dozer-core</artifactId>
    <version>6.2.0</version>
</dependency>
```

2. Run as following code on standalone

```java
public static void main(String[] args) {
	DozerBeanMapperBuilder.buildDefault()
			.map(new A(),new B());
}

```

### Observed Results:

`java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory` is occurred as follow:

```
Exception in thread "main" org.dozer.MappingException: java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	at org.dozer.util.MappingUtils.throwMappingException(MappingUtils.java:81)
	at org.dozer.MappingProcessor.mapGeneral(MappingProcessor.java:209)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:149)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:144)
	at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:148)
	at com.example.dozerdemo.DozerDemoApplication.main(DozerDemoApplication.java:15)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	at org.apache.commons.beanutils.ConvertUtilsBean.<init>(ConvertUtilsBean.java:154)
	at org.apache.commons.beanutils.BeanUtilsBean.<init>(BeanUtilsBean.java:113)
	at org.apache.commons.beanutils.BeanUtilsBean$1.initialValue(BeanUtilsBean.java:64)
	at org.apache.commons.beanutils.BeanUtilsBean$1.initialValue(BeanUtilsBean.java:60)
	at org.apache.commons.beanutils.ContextClassLoaderLocal.get(ContextClassLoaderLocal.java:154)
	at org.apache.commons.beanutils.BeanUtilsBean.getInstance(BeanUtilsBean.java:76)
	at org.apache.commons.beanutils.PropertyUtilsBean.getInstance(PropertyUtilsBean.java:107)
	at org.apache.commons.beanutils.PropertyUtils.getPropertyDescriptors(PropertyUtils.java:518)
	at org.dozer.util.ReflectionUtils.getPropertyDescriptors(ReflectionUtils.java:265)
	at org.dozer.classmap.ClassMapBuilder$AnnotationPropertiesGenerator.apply(ClassMapBuilder.java:400)
	at org.dozer.classmap.ClassMapBuilder.generateMapping(ClassMapBuilder.java:141)
	at org.dozer.classmap.ClassMapBuilder.createDefaultClassMap(ClassMapBuilder.java:114)
	at org.dozer.classmap.ClassMapBuilder.createDefaultClassMap(ClassMapBuilder.java:99)
	at org.dozer.MappingProcessor.getClassMap(MappingProcessor.java:1166)
	at org.dozer.MappingProcessor.mapGeneral(MappingProcessor.java:178)
	... 4 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
```
  
### Expected Results:
I expect one of following.

* Works fine without doing anything (In other words, the `dozer-core` retrieve `jcl-over-sl4fj` as dependency artifact)
* Indicate the `jcl-over-sl4fj` as dependency artifact of `provided` scope in `pom.xml` and add guide about `jcl-over-sl4fj` in docs

WDYT?

**Comment by garethahealy** [comment]
@kazuki43zoo ; can you raise a PR with _jcl-over-sl4fj_ as a dependancy please
