### ISSUE TITLE
CustomConverter - nested object of same type cannot be cast to itself??

### ISSUE THREAD

**Issue by MacGyver27** [DozerMapper/dozer#691]
Hello,

I am facing a blocker type of problem with Dozer custom converter. At the moment I am not able to solve it via dozer mapper but doing it manually works - no extra logic and it works outside custom converter.

* Dozer version: 6.2.0
* OS version: Ubuntu 18.04
* JDK version: 1.8.0_171

Classes - **Source side** representation:
```java
public abstract class NetworkObjectDTOAbstract {

    @JsonProperty("id")
    private Long id;

    @JsonProperty("name")
    private String name;

    @JsonProperty("class_name")
    private String className;

    @JsonProperty("ip")
    private String ip;

    @JsonProperty("netmask")
    private String netmask;
	
}

public class NetworkObjectDTO1 extends NetworkObjectDTOAbstract {

    @JsonProperty("member")
    private MemberDTO member;
}

public class NetworkObjectDTO2 extends NetworkObjectDTOAbstract {

    @JsonProperty("member")
    private List<MemberDTO> member;
}
```
Classes - **Destination side** representation:
```java
public class NetworkObjectDTO {

    @JsonProperty("id")
    private Long id;

    @JsonProperty("name")
    private String name;

    @JsonProperty("class_name")
    private String className;

    @JsonProperty("ip")
    private String ip;

    @JsonProperty("netmask")
    private String netmask;

    @JsonProperty("member")
    private List<MemberDTO> member;
}
```
Dozer **CustomConverter**:
```java
public class MemberToListSimpleConverter implements CustomConverter {

    @Override
    public Object convert(Object dst, Object src, Class<?> dstClass, Class<?> srcClass) {
        if (src instanceof MemberDTO) {
            List<MemberDTO> list = new ArrayList();
            list.add((MemberDTO) src);
            return list;
        }
        if (src instanceof List) {
            return ((List) src).get(0);
        }
        return null;
    }
}
```

**Mapping** definition:
```xml
    <!--Network Object-->
    <!--<mapping>-->
        <!--<class-a>com.att.portalapp.nextgendc.module.arcs.dto.network_object.tufin.NetworkObjectDTOAbstract</class-a>-->
        <!--<class-b>com.att.portalapp.nextgendc.module.arcs.dto.network_object.NetworkObjectDTO</class-b>-->
    <!--</mapping>-->
    <mapping>
        <class-a>com.att.portalapp.nextgendc.module.arcs.dto.network_object.tufin.NetworkObjectDTO1</class-a>
        <class-b>com.att.portalapp.nextgendc.module.arcs.dto.network_object.NetworkObjectDTO</class-b>
        <field custom-converter="com.att.portalapp.nextgendc.module.arcs.converter.MemberToListSimpleConverter">
            <a>member</a>
            <b>member</b>
        </field>
    </mapping>
    <mapping>
        <class-a>com.att.portalapp.nextgendc.module.arcs.dto.network_object.tufin.NetworkObjectDTO2</class-a>
        <class-b>com.att.portalapp.nextgendc.module.arcs.dto.network_object.NetworkObjectDTO</class-b>
        <field>
            <a>member</a>
            <b>member</b>
        </field>
    </mapping>

```

So from seeing the class definition you see I am trying to achieve pretty simple thing.. In case **MemberDTO** is object, make it a list of 1 value - that's it.

However in **CustomConverter** it never enters if clause. I am not getting why? It is the same object at both places.. When I do a test before the if statement in **CustomConverter**: `src = (MemberDTO) src;` it fails on **cannot be cast**  error: `java.lang.ClassCastException: com.***.module.arcs.dto._custom.MemberDTO cannot be cast to com.***.module.arcs.dto._custom.MemberDTO`

From the debug session:
![image](https://user-images.githubusercontent.com/6546231/43458170-ffa55752-947d-11e8-8f19-28ac4adf1a10.png)
![image](https://user-images.githubusercontent.com/6546231/43458191-16be9aca-947e-11e8-9685-9289a593280d.png)

Error stack trace:
```
2018-07-31 05:14:26.114 ERROR 18817 --- [nio-9080-exec-1] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/nextgendc] threw exception [Request processing failed; nested exception is java.lang.ClassCastException: com.***.module.arcs.dto._custom.MemberDTO cannot be cast to com.***.module.arcs.dto._custom.MemberDTO] with root cause

java.lang.ClassCastException: com.***.module.arcs.dto._custom.MemberDTO cannot be cast to com.***.module.arcs.dto._custom.MemberDTO
	at com.***.module.arcs.converter.MemberToListSimpleConverter.convert(MemberToListSimpleConverter.java:13)
	at org.dozer.MappingProcessor.mapUsingCustomConverterInstance(MappingProcessor.java:1041)
	at org.dozer.MappingProcessor.mapUsingCustomConverter(MappingProcessor.java:1068)
	at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:403)
	at org.dozer.MappingProcessor.mapField(MappingProcessor.java:350)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:310)
	at org.dozer.MappingProcessor.mapToDestObject(MappingProcessor.java:259)
	at org.dozer.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:233)
	at org.dozer.MappingProcessor.mapGeneral(MappingProcessor.java:207)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:140)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:135)
	at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:141)
	at com.***.module.arcs.service.NetworkObjectService.lambda$mapDTO$3(NetworkObjectService.java:69)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.***.module.arcs.service.NetworkObjectService.mapDTO(NetworkObjectService.java:69)
	at com.***.module.arcs.service.NetworkObjectService.returnDTO(NetworkObjectService.java:19)
	at com.***.module.arcs.controller.ArcsRestController.getFirewallObjectsByTenant(ArcsRestController.java:250)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.AbstractRequestLoggingFilter.doFilterInternal(AbstractRequestLoggingFilter.java:244)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:112)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.rakugakibox.spring.boot.logback.access.LogbackAccessSecurityAttributesSaveFilter.doFilter(LogbackAccessSecurityAttributesSaveFilter.java:28)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at ch.qos.logback.classic.helpers.MDCInsertingServletFilter.doFilter(MDCInsertingServletFilter.java:49)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.micrometer.spring.web.servlet.MetricsFilter.doFilterInternal(MetricsFilter.java:72)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at net.rakugakibox.spring.boot.logback.access.tomcat.LogbackAccessTomcatValve.invoke(LogbackAccessTomcatValve.java:91)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

Am I missing something? Appreciate any response. Thanks, Michal

**Comment by garethahealy** [comment]
@MacGyver27 ; can you create a github repo with the example and a unit test please? it makes it easier stepping through the code.

**Comment by MacGyver27** [comment]
I could but later. I cant use live example due to company's policies so would have to create it from scratch.. However this is very simple to reproduce - not doing anything use-case specific. Do anything come you your mind I might be doing wrong? Otherwise I will make some demo..

**Comment by MacGyver27** [comment]
Hey, nobody had a look yet? I think I provided a pretty detailed process how to replicate the issue :) Thanks

**Comment by MacGyver27** [comment]
Found where the problem lied.. -> #273

**Comment by garethahealy** [comment]
@MacGyver27 ; going to close this; as from your other comment it seems the config lives in the client app, correct?

**Comment by MacGyver27** [comment]
Yes, correct. thanks
