### ISSUE TITLE
Inner classes doesn't work

### ISSUE THREAD

**Issue by luxiaowan** [DozerMapper/dozer#750]
## Whats your runtime?
* Dozer version: 5.5.1
* OS version: macOS 10.13.6
* JDK version: 1.8.0_161
  
## Whats the problem?
Inner classes doesn't work, Message:Caused by: java.lang.NoSuchMethodException: DozerMapBean$InnerBean.<init>(), because of outside classes must be initialized before internal classes，
_Steps to reproduce:_
1. create java file DozerMapBean.java

@Data
@ToString
public class DozerMapBean {
    private Integer id;
    @Data
    @ToString
    public class InnerBean {
        private Integer id;
    }
}

2. run test class DozerInnerTest.java

public class DozerInnerTest {
    private static DozerBeanMapper MAPPER = new DozerBeanMapper();
    public static void main(String[] args) throws Exception {
        DozerMapBean p = new DozerMapBean();
        p.setId(1);
        MAPPER.map(p, DozerMapBean.InnerBean.class);
    }
}

  
### Observed Results:
Exception in thread "main" org.dozer.MappingException: java.lang.NoSuchMethodException: cc.kevinlu.utils.test.dozer.DozerMapBean$InnerBean.<init>()
	at org.dozer.util.MappingUtils.throwMappingException(MappingUtils.java:82)
	at org.dozer.factory.ConstructionStrategies$ByConstructor.newInstance(ConstructionStrategies.java:276)
	at org.dozer.factory.ConstructionStrategies$ByConstructor.create(ConstructionStrategies.java:260)
	at org.dozer.factory.DestBeanCreator.applyStrategies(DestBeanCreator.java:76)
	at org.dozer.factory.DestBeanCreator.create(DestBeanCreator.java:62)
	at org.dozer.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:195)
	at org.dozer.MappingProcessor.mapGeneral(MappingProcessor.java:170)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:104)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:99)
	at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:120)
	at cc.kevinlu.utils.common.BeanMapper.map(BeanMapper.java:24)
	at cc.kevinlu.utils.test.dozer.DozerInnerTest.main(DozerInnerTest.java:10)
Caused by: java.lang.NoSuchMethodException: cc.kevinlu.utils.test.dozer.DozerMapBean$InnerBean.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.dozer.factory.ConstructionStrategies$ByConstructor.newInstance(ConstructionStrategies.java:272)
	... 10 more
  
### Expected Results:
 print: DozerMapBean.InnerBean(id=1)

**Comment by luxiaowan** [comment]
the exception occurred in org.dozer.factory.ConstructionStrategies$ByConstructor::newInstance, I have modified:

private static <T> T newInstance(Class<T> clazz) {
            //Create using public or private no-arg constructor
            Constructor<T> constructor = null;

            T result = null;
            try {
                List<Class> objs = new ArrayList<>();
                objs.add(clazz);
                while (clazz.isMemberClass()) {
                    clazz = (Class<T>) clazz.getEnclosingClass();
                    objs.add(clazz);
                }
                if (objs.size() == 1) {
                    result = clazz.getConstructor(null).newInstance(null);
                }
                for (int i = objs.size() - 2; i >= 0; i--) {
                    clazz = objs.get(i + 1);
                    constructor = objs.get(i).getDeclaredConstructor(new Class[] { clazz });
                    if (constructor == null) {
                        MappingUtils.throwMappingException("Could not create a new instance of the dest object: "
                                + clazz + ".  Could not find a no-arg constructor for this class.");
                    }
                    if (!constructor.isAccessible()) {
                        constructor.setAccessible(true);
                    }
                    result = constructor.newInstance(result);
                }

            } catch (SecurityException e) {
                MappingUtils.throwMappingException(e);
            } catch (NoSuchMethodException e) {
                MappingUtils.throwMappingException(e);
            } catch (IllegalArgumentException e) {
                MappingUtils.throwMappingException(e);
            } catch (InstantiationException e) {
                MappingUtils.throwMappingException(e);
            } catch (IllegalAccessException e) {
                MappingUtils.throwMappingException(e);
            } catch (InvocationTargetException e) {
                MappingUtils.throwMappingException(e);
            }

            return result;
        }

**Comment by garethahealy** [comment]
@luxiaowan ; can you retest with latest please

**Comment by luxiaowan** [comment]
build the jar by myself, or use the repository of maven?the version of dependency is 6.4.0 now， can I use it for retest?

**Comment by luxiaowan** [comment]
> @luxiaowan ; can you retest with latest please

build the jar by myself, or use the repository of maven?the version of dependency is 6.4.0 now， can I use it for retest?
