### ISSUE TITLE
StackOverflowError when cyclic dependency present in hibernate entities.

### ISSUE THREAD

**Issue by miteshaghera** [DozerMapper/dozer#760]
## Whats your runtime?
* Dozer version: 5.5.1
* OS version: win 10
* JDK version: oracle jdk 1.8.0_201
  
## Whats the problem?
When cyclic referenced entities A->B->A managed by jpa/hibernate are passed to dozer for converting them to DTOs it will go into infinite loop and `StackOverflowError` occurs.

I've already applied `HibernateProxyResolver`.
  
### Observed Results:
After debugging into [`MappingProcessor.mapOrRecurseObject`](https://github.com/DozerMapper/dozer/blob/526845a62778ddc2f4cfb7270246c6c3aeeebfb2/core/src/main/java/org/dozer/MappingProcessor.java#L400), I found that `mappedFields.getMappedValue` does not return already mapped value because still `srcFieldValue` is proxied object of hibernate(in my case).
  
### Expected Results:
`StackOverflowError` should not occur.

**Comment by garethahealy** [comment]
Since you mentioned dozer 5.5.1, please upgrade to latest and retest.

**Comment by miteshaghera** [comment]
@garethahealy Yes, It still persists for 6.5.0. Please find recursive stack trace
`at com.github.dozermapper.core.MappingProcessor.mapCustomObject(MappingProcessor.java:575)
        at com.github.dozermapper.core.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:512)
        at com.github.dozermapper.core.MappingProcessor.addOrUpdateToList(MappingProcessor.java:881)
        at com.github.dozermapper.core.MappingProcessor.addOrUpdateToList(MappingProcessor.java:955)
        at com.github.dozermapper.core.MappingProcessor.mapListToList(MappingProcessor.java:791)
        at com.github.dozermapper.core.MappingProcessor.mapCollection(MappingProcessor.java:641)
        at com.github.dozermapper.core.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:500)
        at com.github.dozermapper.core.MappingProcessor.mapFromFieldMap(MappingProcessor.java:404)
        at com.github.dozermapper.core.MappingProcessor.mapField(MappingProcessor.java:354)
        at com.github.dozermapper.core.MappingProcessor.map(MappingProcessor.java:314)
        at com.github.dozermapper.core.MappingProcessor.mapToDestObject(MappingProcessor.java:263)
        at com.github.dozermapper.core.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:236)
`

**Comment by miteshaghera** [comment]
I tried to debug in library and find that it [`alreadyMappedValue`](https://github.com/DozerMapper/dozer/blob/9a60f6d47e9e4d1fe506871c96ee2e8b861a39a3/core/src/main/java/com/github/dozermapper/core/MappingProcessor.java#L442) is null even though it was mapped in previous cycle.

I think we can fix it by adding line `srcFieldValue = MappingUtils.deProxy(srcFieldValue, this.beanContainer);`
