### ISSUE TITLE
ConcurrentModificationException in MappingProcessor when several threads work with the same collection

### ISSUE THREAD

**Issue by andriimelnyk1** [DozerMapper/dozer#789]
When one thread modifies collection and another thread creates a copy of collection via the call of method org.dozer.Mapper.map, then occur java.util.ConcurrentModificationException

Details:
In method org.dozer.MappingProcessor#addOrUpdateToList(java.lang.Object, org.dozer.fieldmap.FieldMap, java.util.Collection<?>, java.lang.Object, java.lang.Class<?>)
on line 598:
i$.next();
when iterator retrieve next value, then if collection was modified by another thread, then ConcurrentModificationException 

## What's your runtime?
* Dozer version: 5.3.3
* OS version: Linux
* JDK version: 1.8
 
  
### Observed Results:

StackTrace:
```
 Field mapping error -->
  MapId: null
  Type: null
  Source parent class: com.commerce.order.CollectionInfo
  Source field name: collectionOperations
  Source field type: class java.util.ArrayList
  Source field value: [com.commerce.order.CollectionOperation@608f2364(id=19201349), com.commerce.order.CollectionOperation@4b360caf(id=19201354)]
  Dest parent class: kf.order.dto.KFCollectionInfoDTO
  Dest field name: collectionOperations
  Dest field type: java.util.List: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at org.dozer.MappingProcessor.addOrUpdateToList(MappingProcessor.java:757)
	at org.dozer.MappingProcessor.addOrUpdateToList(MappingProcessor.java:841)
	at org.dozer.MappingProcessor.mapListToList(MappingProcessor.java:677)
	at org.dozer.MappingProcessor.mapCollection(MappingProcessor.java:532)
	at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:425)
	at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:333)
	at org.dozer.MappingProcessor.mapField(MappingProcessor.java:279)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:248)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:197)
	at org.dozer.MappingProcessor.mapCustomObject(MappingProcessor.java:486)
	at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:437)
	at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:333)
	at org.dozer.MappingProcessor.mapField(MappingProcessor.java:279)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:248)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:197)
	at org.dozer.MappingProcessor.mapCustomObject(MappingProcessor.java:486)
	at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:437)
	at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:333)
	at org.dozer.MappingProcessor.mapField(MappingProcessor.java:279)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:248)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:197)
	at org.dozer.MappingProcessor.mapCustomObject(MappingProcessor.java:486)
	at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:437)
	at org.dozer.MappingProcessor.addOrUpdateToList(MappingProcessor.java:767)
	at org.dozer.MappingProcessor.addOrUpdateToList(MappingProcessor.java:841)
	at org.dozer.MappingProcessor.mapListToList(MappingProcessor.java:677)
	at org.dozer.MappingProcessor.mapCollection(MappingProcessor.java:532)
	at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:425)
	at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:333)
	at org.dozer.MappingProcessor.mapField(MappingProcessor.java:279)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:248)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:197)
	at org.dozer.MappingProcessor.mapCustomObject(MappingProcessor.java:486)
	at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:437)
	at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:333)
	at org.dozer.MappingProcessor.mapField(MappingProcessor.java:279)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:248)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:197)
	at org.dozer.MappingProcessor.mapCustomObject(MappingProcessor.java:486)
	at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:437)
	at org.dozer.MappingProcessor.addOrUpdateToList(MappingProcessor.java:767)
	at org.dozer.MappingProcessor.addOrUpdateToList(MappingProcessor.java:841)
	at org.dozer.MappingProcessor.mapListToList(MappingProcessor.java:677)
	at org.dozer.MappingProcessor.mapCollection(MappingProcessor.java:532)
	at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:425)
	at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:333)
	at org.dozer.MappingProcessor.mapField(MappingProcessor.java:279)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:248)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:197)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:187)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:124)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:119)
	at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:113)
```

**Comment by andriimelnyk1** [comment]
Possible solution:
You should add some config property to mapping, let's name it "copyCollectionConcurrent", which allow turning on concurrent work with the list, like this:

```
 private List<?> addOrUpdateToList(Object srcObj, FieldMap fieldMap, Collection<?> srcCollectionValue, Object destObj, Class<?> destEntryType) {
        List<Object> mappedElements = new ArrayList();
        Object field = fieldMap.getDestValue(destObj);
        List result = prepareDestinationList(srcCollectionValue, field);
        Class<?> prevDestEntryType = null;
        **Iterator i$ = copyCollectionConcurrent?new CopyOnWriteArrayList(srcCollectionValue).iterator():
srcCollectionValue.iterator();**

```
