### ISSUE TITLE
protobuf3 enum map error

### ISSUE THREAD

**Issue by LawlietNot** [DozerMapper/dozer#805]
## Are you in the right place?
* For issues or feature requests related to the code **in this repository** file a Github issue.
* For general technical questions, post a question on [Google Groups](https://groups.google.com/forum/?fromgroups=#!forum/dozer-mapper).

## Whats your runtime?
* Dozer version: 6.5.0
* OS version: macOS Catalina 10.15.7
* JDK version: 1.8 Hotspot
  
## Whats the problem?
_Steps to reproduce:_
1. edit protobuf3 file
```
syntax = "proto3";
package test;
// Because other languages are written unset 
// option java_outer_classname = "TestOuterClass";
enum EnumVal{
  ONE = 1;
  TWO = 2;
}
```

2. map protobufEnumField from Proto 
  
### Observed Results:
```
com.github.dozermapper.core.MappingException: java.lang.ClassNotFoundException: test//EnumVal
	at com.github.dozermapper.core.util.MappingUtils.throwMappingException(MappingUtils.java:78)
	at com.github.dozermapper.core.util.DefaultClassLoader.loadClass(DefaultClassLoader.java:40)
	at com.github.dozermapper.core.util.MappingUtils.loadClass(MappingUtils.java:222)
	at com.github.dozermapper.protobuf.util.ProtoUtils.getEnumClassByEnumDescriptor(ProtoUtils.java:238)
	at com.github.dozermapper.protobuf.util.ProtoUtils.unwrapEnums(ProtoUtils.java:279)
	at com.github.dozermapper.protobuf.util.ProtoUtils.unwrapEnums(ProtoUtils.java:295)
	at com.github.dozermapper.protobuf.propertydescriptor.ProtoFieldPropertyDescriptor.getSimplePropertyValue(ProtoFieldPropertyDescriptor.java:140)
	at com.github.dozermapper.protobuf.propertydescriptor.ProtoFieldPropertyDescriptor.getPropertyValue(ProtoFieldPropertyDescriptor.java:118)
	at com.github.dozermapper.core.fieldmap.FieldMap.getSrcFieldValue(FieldMap.java:89)
```
### Expected Results:
correct map

## Link to GitHub repo with Unit test
_The easiest way for us to fix issues, is if you provide a GitHub repo, using the latest release and a simple unit test._
TODO

**Comment by garethahealy** [comment]
@LawlietNot ; still an issue?

**Comment by LawlietNot** [comment]
I found that this was due to an option setting configuration issue
Incorrect configuration will result in ClassNotFoundException
