### ISSUE TITLE
MapToMap mapping failed if source field is hibernate PersistenceMap

### ISSUE THREAD

**Issue by Spikhalskiy** [DozerMapper/dozer#81]
If map a hibernate entity with map to pojo class with dest map field Dozer tries to create a PersistenceMap in destination class and failed with lazy initialization exception.

```
ERROR [MappingProcessor] - Field mapping error -->
  MapId: null
  Type: null
  Source parent class: xxx.Model
  Source field name: attributes
  Source field type: class org.hibernate.collection.internal.PersistentMap
  Source field value: {phone=33-33-22}
  Dest parent class: xxx.ModelDTO
  Dest field name: attributes
  Dest field type: java.util.Map 
org.hibernate.LazyInitializationException: failed to lazily initialize a collection, no session or session was closed
    at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:489)
    at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationExceptionIfNotConnected(AbstractPersistentCollection.java:447)
    at org.hibernate.collection.internal.AbstractPersistentCollection.readElementByIndex(AbstractPersistentCollection.java:222)
    at org.hibernate.collection.internal.PersistentMap.get(PersistentMap.java:165)
    at org.dozer.MappingProcessor.mapMap(MappingProcessor.java:601)
```

**Comment by vitalidze** [comment]
Hi

We are facing exactly same issue after updating to 5.5.1: dozer converts hibernate `PersistentMap` to the `PersistentMap` and not `HashMap` as it was doing before update. We need latest version because we are facing [concurrency issue](http://sourceforge.net/p/dozer/bugs/241/) but I guess will need to write a custom converters for hibernate's collection types.

I believe the problem with `Map` can be fixed by updating this line https://github.com/DozerMapper/dozer/blob/master/core/src/main/java/org/dozer/MappingProcessor.java#L589 to something like this:

````java
DestBeanCreator.create(srcMapValue.getClass(), Map.class);
````

**Comment by garethahealy** [comment]
@Spikhalskiy ; is this still an issue? if so, can you create a github repo, that includes a unit test showing this behaviour and link it here.

**Comment by garethahealy** [comment]
Closing due to inactivity.
