### ISSUE TITLE
High CPU in combination with openjdk11 and log4j2

### ISSUE THREAD

**Issue by bgoorden** [DozerMapper/dozer#810]
## Whats your runtime?
* Dozer version: 6.5.0
* OS version: Windows server 2016
* JDK version: AdoptOpenJDK11.0.8
* Log4j2 version 2.14.0
  
## Whats the problem?
We are using log4j2 in combination with dozer mapper in our project. In OpenJDK11 there is an issue that causes high cpu while [stackwalking](https://bugs.openjdk.java.net/browse/JDK-8222942). Several issues have been reported in combination with [log4j2](https://issues.apache.org/jira/browse/LOG4J2-2940).

We are encountering high cpu in production at this moment. In stackdumps we almost always see dozer stackwalking (see stacktrace). This seems to be caused by creating loggers in 'MappingProcessor' and 'LogMsgFactory', each time the dozer .map() function is called.
I did a test and changed the loggers to static in the two mentioned classes. This improved performance a lot for us. When mapping 10000 small objects (with a few strings in them), runtimes went down from ~6s to ~3s.

Is there a reason the loggers are not created static and can this be changed for performance?

`at java.lang.StackStreamFactory$AbstractStackWalker.fetchStackFrames(java.base@11.0.8/Native Method)
	at java.lang.StackStreamFactory$AbstractStackWalker.fetchStackFrames(java.base@11.0.8/Unknown Source)
	at java.lang.StackStreamFactory$AbstractStackWalker.getNextBatch(java.base@11.0.8/Unknown Source)
	at java.lang.StackStreamFactory$AbstractStackWalker.peekFrame(java.base@11.0.8/Unknown Source)
	at java.lang.StackStreamFactory$AbstractStackWalker.hasNext(java.base@11.0.8/Unknown Source)
	at java.lang.StackStreamFactory$StackFrameTraverser.tryAdvance(java.base@11.0.8/Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(java.base@11.0.8/Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(java.base@11.0.8/Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(java.base@11.0.8/Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(java.base@11.0.8/Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(java.base@11.0.8/Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(java.base@11.0.8/Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(java.base@11.0.8/Unknown Source)
	at org.apache.logging.log4j.util.StackLocator.lambda$getCallerClass$6(StackLocator.java:58)
	at org.apache.logging.log4j.util.StackLocator$$Lambda$199/0x0000000800751c40.apply(Unknown Source)
	at java.lang.StackStreamFactory$StackFrameTraverser.consumeFrames(java.base@11.0.8/Unknown Source)
	at java.lang.StackStreamFactory$AbstractStackWalker.doStackWalk(java.base@11.0.8/Unknown Source)
	at java.lang.StackStreamFactory$AbstractStackWalker.callStackWalk(java.base@11.0.8/Native Method)
	at java.lang.StackStreamFactory$AbstractStackWalker.beginStackWalk(java.base@11.0.8/Unknown Source)
	at java.lang.StackStreamFactory$AbstractStackWalker.walk(java.base@11.0.8/Unknown Source)
	at java.lang.StackWalker.walk(java.base@11.0.8/Unknown Source)
	at org.apache.logging.log4j.util.StackLocator.getCallerClass(StackLocator.java:57)
	at org.apache.logging.log4j.util.StackLocatorUtil.getCallerClass(StackLocatorUtil.java:67)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:45)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:48)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:270)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
	at com.github.dozermapper.core.util.LogMsgFactory.<init>(LogMsgFactory.java:32)
	at com.github.dozermapper.core.MappingProcessor.<init>(MappingProcessor.java:97)
	at com.github.dozermapper.core.DozerBeanMapper.getMappingProcessor(DozerBeanMapper.java:141)
	at com.github.dozermapper.core.DozerBeanMapper.map(DozerBeanMapper.java:129)`

**Comment by garethahealy** [comment]
@bgoorden ; if you want to open a PR to fix, am happy to review/merge.

**Comment by bgoorden** [comment]
Thank you for the response @garethahealy. I created a pull request for this issue: https://github.com/DozerMapper/dozer/pull/823

**Comment by Floww** [comment]
Sorry to comment 3 years later... I noticed a similar overconsumption but on the class GetterSetterPropertyDescriptor : https://github.com/DozerMapper/dozer/blob/8efd82f65da118abfa4a5c953bd8dc1bda3bb112/core/src/main/java/com/github/dozermapper/core/propertydescriptor/GetterSetterPropertyDescriptor.java#L45

Shouldn't all cases be corrected?
