### ISSUE TITLE
ClassCastException when using generified Lists

### ISSUE THREAD

**Issue by alapite** [DozerMapper/dozer#82]
Hi,

I'm trying to use Dozer to map two objects which internally contain Lists with wildcard types, and I'm getting errors of the following type:

java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.WildcardTypeImpl cannot be cast to java.lang.Class
    at org.dozer.util.ReflectionUtils.determineGenericsType(ReflectionUtils.java:401)
    at org.dozer.util.ReflectionUtils.determineGenericsType(ReflectionUtils.java:389)
    at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.genericType(GetterSetterPropertyDescriptor.java:354)
    at org.dozer.fieldmap.FieldMap.getGenericType(FieldMap.java:145)
    at org.dozer.MappingProcessor.mapCollection(MappingProcessor.java:505)
    at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:434)
    at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:342)
    at org.dozer.MappingProcessor.mapField(MappingProcessor.java:288)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:248)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:197)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:187)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:124)
    at org.dozer.MappingProcessor.map(MappingProcessor.java:119)
    at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:120)

It seems that the issue has been raised before on your previous SourceForge project (see http://sourceforge.net/tracker/index.php?func=detail&aid=3487763&group_id=133517&atid=727368), but for some reason it wasn't migrated over. The fix suggested in the bug report seems reasonable enough to me: do you have any intention of implementing it, or will some other change take care of the problem?

**Comment by garethahealy** [comment]
@alapite ; is this still an issue? if so, can you create a github repo, that includes a unit test showing this behaviour and link it here.

**Comment by garethahealy** [comment]
Closing due to inactivity.
