### ISSUE TITLE
Cannot convert from java.time.Instant to java.utli.Date anymore

### ISSUE THREAD

**Issue by Robbe64** [DozerMapper/dozer#826]
## Whats your runtime?
* Dozer version: 6.5.2
* OS version: Windows 10 20H2
* JDK version: 14.0.1
  
## Whats the problem?
I mapped a Instance to a Date.
  
### Observed Results:
Getting the following Exception  
```
com.github.dozermapper.core.converters.ConversionException: Unable to determine time in millis of source object] with root cause

java.lang.NumberFormatException: For input string: "2018-12-09T08:47:00Z"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68) ~[na:na]
        at java.base/java.lang.Long.parseLong(Long.java:707) ~[na:na]
        at java.base/java.lang.Long.parseLong(Long.java:832) ~[na:na]
        at com.github.dozermapper.core.converters.DateConverter.convert(DateConverter.java:77) ~[dozer-core-6.5.2.jar:6.5.2]
        at com.github.dozermapper.core.converters.PrimitiveOrWrapperConverter.convert(PrimitiveOrWrapperConverter.java:84) ~[dozer-core-6.5.2.jar:6.5.2]
        at com.github.dozermapper.core.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:496) ~[dozer-core-6.5.2.jar:6.5.2]
        at com.github.dozermapper.core.MappingProcessor.mapFromFieldMap(MappingProcessor.java:404) ~[dozer-core-6.5.2.jar:6.5.2]
        at com.github.dozermapper.core.MappingProcessor.mapField(MappingProcessor.java:354) ~[dozer-core-6.5.2.jar:6.5.2]
        at com.github.dozermapper.core.MappingProcessor.map(MappingProcessor.java:314) ~[dozer-core-6.5.2.jar:6.5.2]
        at com.github.dozermapper.core.MappingProcessor.mapToDestObject(MappingProcessor.java:263) ~[dozer-core-6.5.2.jar:6.5.2]
        at com.github.dozermapper.core.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:236) ~[dozer-core-6.5.2.jar:6.5.2]
        at com.github.dozermapper.core.MappingProcessor.mapGeneral(MappingProcessor.java:209) ~[dozer-core-6.5.2.jar:6.5.2]
        at com.github.dozermapper.core.MappingProcessor.map(MappingProcessor.java:132) ~[dozer-core-6.5.2.jar:6.5.2]
        at com.github.dozermapper.core.MappingProcessor.map(MappingProcessor.java:127) ~[dozer-core-6.5.2.jar:6.5.2]
        at com.github.dozermapper.core.DozerBeanMapper.map(DozerBeanMapper.java:129) ~[dozer-core-6.5.2.jar:6.5.2]
```
  
### Expected Results:
It should be converted to Date

**Comment by garethahealy** [comment]
@Robbe64 ; since the issue title includes _"... anymore"_ ; at what version did it work?
