### ISSUE TITLE
java.util.HashSet cannot be cast to java.util.List

### ISSUE THREAD

**Issue by irobertson** [DozerMapper/dozer#830]
Note that this appears to be the same as #214. That was closed, but does not appear to have been fixed.

## Whats your runtime?
* Dozer version: 6.5.1
* OS version: MacOS 11.6
* JDK version: 1.8
  
## Whats the problem?
_Steps to reproduce:_
1. Compile and run the following class:
```
package dozer.test;

import com.github.dozermapper.core.DozerBeanMapperBuilder;
import com.github.dozermapper.core.Mapper;

import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public class DozerBug {
    public static class Source {
        Map<String, Set<String>> map;

        public Map<String, Set<String>> getMap() { return map; }
        public void setMap(Map<String, Set<String>> map) { this.map = map; }
    }

    public static class Target {
        Map<String, Set<String>> map;

        public Map<String, Set<String>> getMap() { return map; }
        public void setMap(Map<String, Set<String>> map) { this.map = map; }
    }

    public static void main(String[] args) {
        final Mapper mapper = DozerBeanMapperBuilder.create().build();
        Source source = new Source();
        Map<String, Set<String>> sourceMap = new HashMap<>();
        sourceMap.put("foo", new HashSet<>(Arrays.asList("bar")));
        source.setMap(sourceMap);
        mapper.map(source, Target.class);
    }
}
```
  
### Observed Results:
```
14:54:22.168 [main] ERROR com.github.dozermapper.core.MappingProcessor - Field mapping error -->
  MapId: null
  Type: null
  Source parent class: dozer.test.DozerBug$Source
  Source field name: map
  Source field type: class java.util.HashMap
  Source field value: {foo=[bar]}
  Dest parent class: dozer.test.DozerBug$Target
  Dest field name: map
  Dest field type: java.util.Map
java.lang.ClassCastException: java.util.HashSet cannot be cast to java.util.List
	at com.github.dozermapper.core.MappingProcessor.mapCollection(MappingProcessor.java:636) ~[dozer-core-6.5.1.jar:?]
	at com.github.dozermapper.core.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:500) ~[dozer-core-6.5.1.jar:?]
	at com.github.dozermapper.core.MappingProcessor.mapMap(MappingProcessor.java:666) ~[dozer-core-6.5.1.jar:?]
	at com.github.dozermapper.core.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:456) ~[dozer-core-6.5.1.jar:?]
	at com.github.dozermapper.core.MappingProcessor.mapFromFieldMap(MappingProcessor.java:404) ~[dozer-core-6.5.1.jar:?]
	at com.github.dozermapper.core.MappingProcessor.mapField(MappingProcessor.java:354) [dozer-core-6.5.1.jar:?]
	at com.github.dozermapper.core.MappingProcessor.map(MappingProcessor.java:314) [dozer-core-6.5.1.jar:?]
	at com.github.dozermapper.core.MappingProcessor.mapToDestObject(MappingProcessor.java:263) [dozer-core-6.5.1.jar:?]
	at com.github.dozermapper.core.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:236) [dozer-core-6.5.1.jar:?]
	at com.github.dozermapper.core.MappingProcessor.mapGeneral(MappingProcessor.java:209) [dozer-core-6.5.1.jar:?]
	at com.github.dozermapper.core.MappingProcessor.map(MappingProcessor.java:132) [dozer-core-6.5.1.jar:?]
	at com.github.dozermapper.core.MappingProcessor.map(MappingProcessor.java:127) [dozer-core-6.5.1.jar:?]
	at com.github.dozermapper.core.DozerBeanMapper.map(DozerBeanMapper.java:129) [dozer-core-6.5.1.jar:?]
	at dozer.test.DozerBug.main(DozerBug.java:33) [SojuCourseARestService/:?]
Exception in thread "main" java.lang.ClassCastException: java.util.HashSet cannot be cast to java.util.List
	at com.github.dozermapper.core.MappingProcessor.mapCollection(MappingProcessor.java:636)
	at com.github.dozermapper.core.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:500)
	at com.github.dozermapper.core.MappingProcessor.mapMap(MappingProcessor.java:666)
	at com.github.dozermapper.core.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:456)
	at com.github.dozermapper.core.MappingProcessor.mapFromFieldMap(MappingProcessor.java:404)
	at com.github.dozermapper.core.MappingProcessor.mapField(MappingProcessor.java:354)
	at com.github.dozermapper.core.MappingProcessor.map(MappingProcessor.java:314)
	at com.github.dozermapper.core.MappingProcessor.mapToDestObject(MappingProcessor.java:263)
	at com.github.dozermapper.core.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:236)
	at com.github.dozermapper.core.MappingProcessor.mapGeneral(MappingProcessor.java:209)
	at com.github.dozermapper.core.MappingProcessor.map(MappingProcessor.java:132)
	at com.github.dozermapper.core.MappingProcessor.map(MappingProcessor.java:127)
	at com.github.dozermapper.core.DozerBeanMapper.map(DozerBeanMapper.java:129)
	at dozer.test.DozerBug.main(DozerBug.java:33)
```
  
### Expected Results:
I expected the conversion to succeed.

## Link to GitHub repo with Unit test
_The easiest way for us to fix issues, is if you provide a GitHub repo, using the latest release and a simple unit test._

**Comment by a5613150** [comment]
I have also encountered this issue, haven't I fixed it yet
